#!/usr/bin/env bash
# ==============================================================================
# Hike WebAssembly Safe Obfuscator (Bash Shell Script Edition)
# ------------------------------------------------------------------------------
# Usage:
#   ./build-obfuscate.sh --export-symbols symbols.json
#   ./build-obfuscate.sh --symbols symbols.json --runtime runtime.js --out runtime.min.js
# ==============================================================================

set -e

# Default values
SYMBOLS_FILE="sample_symbols.json"
RUNTIME_FILE="runtime.js"
OUTPUT_FILE="runtime.min.js"
HIKE_SRC=""
WASM_OUT=""

# Parse command line flags
while [[ $# -gt 0 ]]; do
  case "$1" in
    --export-symbols|--symbols)
      SYMBOLS_FILE="$2"
      shift 2
      ;;
    --runtime)
      RUNTIME_FILE="$2"
      shift 2
      ;;
    --out|--runtime-out)
      OUTPUT_FILE="$2"
      shift 2
      ;;
    --src)
      HIKE_SRC="$2"
      shift 2
      ;;
    --wasm-out)
      WASM_OUT="$2"
      shift 2
      ;;
    -h|--help)
      echo "Hike WebAssembly Safe Obfuscator Shell Pipeline"
      echo "Options:"
      echo "  --export-symbols <path>  Path to symbols file generated by hikec"
      echo "  --runtime <path>         Target runtime JS file (default: runtime.js)"
      echo "  --out <path>             Obfuscated output JS file (default: runtime.min.js)"
      echo "  --src <path>             (Optional) Hike source file to compile with hikec"
      echo "  --wasm-out <path>        (Optional) Output Wasm path"
      exit 0
      ;;
    *)
      echo "[ERROR] Unknown option: $1"
      exit 1
      ;;
  esac
done

echo "=================================================================="
echo " Hike Wasm Safe Obfuscator Pipeline (Bash Shell Script)"
echo "=================================================================="

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Step 1: Optional Hikec compilation
if [[ -n "$HIKE_SRC" && -n "$WASM_OUT" ]]; then
    if command -v hikec >/dev/null 2>&1; then
        echo "[INFO] Compiling Hike source with --export-symbols: $HIKE_SRC -> $WASM_OUT"
        hikec build -target wasm32 "$HIKE_SRC" -o "$WASM_OUT" --export-symbols "$SYMBOLS_FILE"
    else
        echo "[WARN] hikec command not found in PATH. Skipping compilation step."
    fi
fi

# Step 2: Optional wasm-strip
if [[ -n "$WASM_OUT" && -f "$WASM_OUT" ]]; then
    if command -v wasm-strip >/dev/null 2>&1; then
        echo "[INFO] Stripping Wasm debug symbols with wasm-strip: $WASM_OUT"
        wasm-strip "$WASM_OUT"
    fi
fi

# Step 3: Run Obfuscation via available JS engine (Deno / Node / Standalone)
if command -v deno >/dev/null 2>&1; then
    echo "[INFO] Executing obfuscation via Deno engine..."
    deno run -A "$SCRIPT_DIR/build-obfuscate-standalone.js" \
        --export-symbols "$SYMBOLS_FILE" \
        --runtime "$RUNTIME_FILE" \
        --runtime-out "$OUTPUT_FILE"
elif command -v node >/dev/null 2>&1; then
    echo "[INFO] Executing obfuscation via Node.js engine..."
    node "$SCRIPT_DIR/build-obfuscate-standalone.js" \
        --export-symbols "$SYMBOLS_FILE" \
        --runtime "$RUNTIME_FILE" \
        --runtime-out "$OUTPUT_FILE"
else
    echo "[ERROR] Neither Deno nor Node.js runtime was found in PATH."
    echo "[HINT] Please install Deno (https://deno.land) or Node.js to execute the pipeline."
    exit 1
fi

echo "=================================================================="
echo "[SUCCESS] Obfuscation pipeline completed! Output: $OUTPUT_FILE"
echo "=================================================================="
