/**
 * Hike Language Unified WebAssembly Runtime (runtime.js)
 * Auto-generated by hikec - Supports the Main Thread context.
 */

// モジュールスコープ変数: WASMが要求するヒープメモリサイズ (KB単位)
let heapSizeKB = 256;

// =============================================================================
// 2. メインスレッド コンテキスト (ブラウザ DOM / クライアント側)
// =============================================================================
// Keep the same runtime usable from browser pages and Node-based E2E tests.
// Node does not define window, but it can still load the generated runtime
// through CommonJS.
if (typeof window !== 'undefined' || (typeof module !== 'undefined' && module.exports)) {
    // Lightweight main-thread runtime. Application-specific host functions
    // are injected from jfunc declarations in the Hike source program.
    class HikeRuntime {
        constructor(options = {}) {
            this.wasmUrl = options.wasmUrl || 'main.wasm';
            this.instance = null;
            this.memory = null;
            this.onLog = options.onLog || (() => {});
            this.onFrame = options.onFrame || (() => {});
            this.frame = 0;
            this.frameCount = 0;
        }

        log(event, details = {}) {
            this.onLog(event, details);
        }

        imports() {
            const runtime = this;
            const env = {
                malloc: (size) => runtime.malloc(size),
                calloc: (count, size) => {
                    const total = Number(count) * Number(size);
                    const ptr = runtime.malloc(total);
                    new Uint8Array(runtime.memory.buffer, ptr, total).fill(0);
                    return ptr;
                },
                free: () => {},
                hike_thread_spawn: (fnIdx, paramPtr) => {
                    const table = runtime.instance && (runtime.instance.exports.__indirect_function_table || runtime.instance.exports.table);
                    const thunk = table && table.get(Number(fnIdx));
                    if (!thunk) return -1;
                    thunk(paramPtr);
                    return 0;
                },
                hike_event_create: () => 1,
                hike_event_signal: () => {},
                hike_event_wait: () => 0,
                hike_event_destroy: () => {},
                hike_sleep_ms: () => {},
                hike_now_ns: () => BigInt(Math.floor(performance.now() * 1000000))
            };

            return { env };
        }

        malloc(size) {
            if (this.heap === undefined) {
                const base = this.instance && this.instance.exports.__heap_base;
                this.heap = base ? Number(base.value || base) : 65536;
            }
            const ptr = this.heap;
            this.heap += (Number(size) + 15) & ~15;
            if (this.instance && this.memory && this.heap > this.memory.buffer.byteLength) {
                const missing = this.heap - this.memory.buffer.byteLength;
                this.memory.grow(Math.ceil(missing / 65536));
            }
            return ptr;
        }

        async load() {
            this.log('wasm-load:begin', { url: this.wasmUrl });
            const response = await fetch(this.wasmUrl);
            if (!response.ok) throw new Error('Failed to fetch ' + this.wasmUrl + ': ' + response.status);
            this.log('wasm-load:response', { ok: response.ok, status: response.status, contentLength: response.headers.get('content-length') });
            const bytes = await response.arrayBuffer();
            this.log('wasm-load:bytes', { byteLength: bytes.byteLength });
            const memory = new WebAssembly.Memory({ initial: 2, maximum: 256 });
            const imports = this.imports();
            imports.env.memory = memory;
            const result = await WebAssembly.instantiate(bytes, imports);
            this.instance = result.instance;
            this.memory = this.instance.exports.memory || memory;
            this.log('WebAssembly.instantiate:returned', {
                exports: Object.keys(this.instance.exports),
                imports: WebAssembly.Module.imports(await WebAssembly.compile(bytes)).map((item) => item.name)
            });
            this.log('wasm-memory:ready', { byteLength: this.memory.buffer.byteLength });
            if (typeof this.instance.exports.InitApp === 'function') {
                this.log('wasm.exports.InitApp:begin', {});
                this.instance.exports.InitApp();
                this.log('wasm.exports.InitApp:return', {});
            }
            if (typeof this.instance.exports.RenderFrame === 'function') {
                const draw = (time) => {
                    if (this.instance) {
                        const angle = time / 1000;
                        const frame = ++this.frameCount;
                        this.onFrame({ frame, time, angle });
                        this.instance.exports.RenderFrame(angle);
                    }
                    this.frame = requestAnimationFrame(draw);
                };
                this.frame = requestAnimationFrame(draw);
            }
            return this.instance.exports;
        }

        stop() {
            if (this.frame) cancelAnimationFrame(this.frame);
            this.frame = 0;
        }
    }

    if (typeof window !== 'undefined') window.HikeRuntime = HikeRuntime;

    class HikeConcurrentRuntime {
        /**
         * @param {Object} options
         * @param {string} [options.wasmUrl='main.wasm']
         * @param {string} [options.scriptUrl='runtime.js'] - 自身のスクリプトファイルパス
         * @param {number} [options.heapSizeKB=256]
         * @param {Function} [options.onResult]
         * @param {Function} [options.onLog]
         */
        constructor(options = {}) {
            this.wasmUrl = options.wasmUrl || 'main.wasm';
            this.scriptUrl = options.scriptUrl || 'runtime.js';
            this.heapSizeKB = options.heapSizeKB || 256;
            this.onResult = options.onResult || (() => {});
            this.onLog = options.onLog || (() => {});
            this.worker = null;
            this.memory = null;
            globalThis.__hikeActiveRuntime = this;
        }

        /**
         * 外部からヒープサイズを変更するAPI
         */
        setHeapSizeKB(sizeKB) {
            this.heapSizeKB = Number(sizeKB);
            if (this.worker) {
                this.worker.postMessage({ type: 'setHeapSizeKB', sizeKB: this.heapSizeKB });
            }
        }

        getHeapSizeKB() {
            return this.heapSizeKB;
        }

        /**
         * runtime.js 自身を Worker として起動
         */
        async start() {
            this.onLog('Hike Concurrent Engine (runtime.js) を起動中...');

            // runtime.js 自体を Worker スレッドとしてインスタンス化
            this.worker = new Worker(this.scriptUrl + '?t=' + Date.now());

            this.worker.onmessage = (e) => {
                const { type, sum, mul, message } = e.data;
                if (type === 'log') {
                    this.onLog(message);
                } else if (type === 'result') {
                    this.onResult(sum, mul);
                }
            };

            this.memory = new WebAssembly.Memory({
                initial: 256,
                maximum: 512,
                shared: true
            });

            const res = await fetch(this.wasmUrl);
            if (!res.ok) {
                throw new Error(`Failed to fetch WASM: ${res.statusText}`);
            }
            const wasmBytes = await res.arrayBuffer();

            this.worker.postMessage({
                type: 'init',
                wasmBytes: wasmBytes,
                memory: this.memory,
                heapSizeKB: this.heapSizeKB
            });
        }

        terminate() {
            if (this.worker) {
                this.worker.terminate();
                this.worker = null;
            }
        }
    }

    // グローバル公開API
    if (typeof window !== 'undefined') window.HikeConcurrentRuntime = HikeConcurrentRuntime;
    globalThis.setHikeHeapSizeKB = (sizeKB) => {
        heapSizeKB = Number(sizeKB);
        if (globalThis.__hikeActiveRuntime) {
            globalThis.__hikeActiveRuntime.setHeapSizeKB(heapSizeKB);
        }
    };
    globalThis.getHikeHeapSizeKB = () => heapSizeKB;

    if (typeof module !== 'undefined' && module.exports) {
        module.exports = { HikeRuntime, HikeConcurrentRuntime };
    }
}
	